// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 5.3.1 by TAF Team.
// Generated from `/data/user/xuzhengwei/upload/Hello.jce'
// **********************************************************************

var assert    = require('assert');
var TafStream = require('@taf/taf-stream');
var TafError  = require('@taf/taf-rpc').error;

if(TafStream.JceStruct == undefined){
TafStream.JceStruct = function() {
this._jce_double_precision_ = -1;
}
TafStream.JceStruct.prototype.setPrecision = function(d) {
if ((d == -1) || (d >= 0 && d <= 15)) {
this._jce_double_precision_ = d;
return true;
}
return false;
}
TafStream.JceStruct.prototype.resetPrecision = function() { this._jce_double_precision_ = -1;}
TafStream.JceStruct.prototype.hasSetPrecision = function() { return (this._jce_double_precision_ >= 0 && this._jce_double_precision_ <= 15);}
TafStream.JceStruct.prototype.getPrecision = function() { return this._jce_double_precision_; }
}

var Test = Test || {};
module.exports.Test = Test;


Test.HelloWorldReq = function() {
    this.data = "";
    this._classname = "Test.HelloWorldReq";
};
Test.HelloWorldReq.prototype = new TafStream.JceStruct();
Test.HelloWorldReq._classname = "Test.HelloWorldReq";

Test.HelloWorldReq._write = function (os, tag, value) { os.writeStruct(tag, value); }
Test.HelloWorldReq._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
Test.HelloWorldReq._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new Test.HelloWorldReq();
    tmp.data = is.readString(0, false, "");
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
Test.HelloWorldReq.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    if (this.data != undefined && this.data != "") {
        os.writeString(0, this.data);
    }
    os.resumePrecision && os.resumePrecision();
};
Test.HelloWorldReq.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
Test.HelloWorldReq.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
Test.HelloWorldReq.prototype.toObject = function() { 
    var tmp = {};

    tmp.data = this.data;
    
    return tmp;
}
Test.HelloWorldReq.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("data") || (this.data = json.data);
}
Test.HelloWorldReq.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
Test.HelloWorldReq.new = function () {
    return new Test.HelloWorldReq();
}
Test.HelloWorldReq.create = function (is) {
    return Test.HelloWorldReq._readFrom(is);
}

Test.HelloWorldRsp = function() {
    this.iRet = 0;
    this.message = "";
    this._classname = "Test.HelloWorldRsp";
};
Test.HelloWorldRsp.prototype = new TafStream.JceStruct();
Test.HelloWorldRsp._classname = "Test.HelloWorldRsp";

Test.HelloWorldRsp._write = function (os, tag, value) { os.writeStruct(tag, value); }
Test.HelloWorldRsp._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
Test.HelloWorldRsp._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new Test.HelloWorldRsp();
    tmp.iRet = is.readInt32(0, false, 0);
    tmp.message = is.readString(1, false, "");
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
Test.HelloWorldRsp.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    if (this.iRet != undefined && this.iRet != 0) {
        os.writeInt32(0, this.iRet);
    }
    if (this.message != undefined && this.message != "") {
        os.writeString(1, this.message);
    }
    os.resumePrecision && os.resumePrecision();
};
Test.HelloWorldRsp.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
Test.HelloWorldRsp.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
Test.HelloWorldRsp.prototype.toObject = function() { 
    var tmp = {};

    tmp.iRet = this.iRet;
    tmp.message = this.message;
    
    return tmp;
}
Test.HelloWorldRsp.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("iRet") || (this.iRet = json.iRet);
    !json.hasOwnProperty("message") || (this.message = json.message);
}
Test.HelloWorldRsp.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
Test.HelloWorldRsp.new = function () {
    return new Test.HelloWorldRsp();
}
Test.HelloWorldRsp.create = function (is) {
    return Test.HelloWorldRsp._readFrom(is);
}

Test.HelloImp = function () { 
    this._name   = undefined;
    this._worker = undefined;
}

Test.HelloImp.prototype.initialize = function () { 
    //TODO:
}

Test.HelloImp.prototype.onDispatch = function (current, FuncName, BinBuffer) { 
    switch (FuncName) {
        case 'test' : {
            current.sendResponse = function (_ret) {
                if (current.getRequestVersion() === TafStream.Wup.WUP_VERSION) {
                    var wup = new TafStream.UniAttribute();
                    wup.wupVersion = current.getRequestVersion();
                    wup.writeInt32("", _ret);

                    current.doResponse(wup.encode());
                } else {
                    var os = new TafStream.JceOutputStream();
                    os.writeInt32(0, _ret);

                    current.doResponse(os.getBinBuffer());
                }
            }

            this.test(current);

            return TafError.SUCCESS;
        }
        case 'helloWorld' : {
            if (current.getRequestVersion() === TafStream.Wup.WUP_VERSION) {
                var wup = new TafStream.UniAttribute();
                wup.wupVersion = current.getRequestVersion();
                wup.decode(BinBuffer);
                var stReq = wup.readStruct("stReq", Test.HelloWorldReq);
                var stRsp = wup.readStruct("stRsp", Test.HelloWorldRsp, new Test.HelloWorldRsp());
            } else {
                var is = new TafStream.JceInputStream(BinBuffer);
                var stReq = is.readStruct(1, true, Test.HelloWorldReq);
                var stRsp = is.readStruct(2, false, Test.HelloWorldRsp);
            }
            current.sendResponse = function (_ret, stRsp) {
                if (current.getRequestVersion() === TafStream.Wup.WUP_VERSION) {
                    var wup = new TafStream.UniAttribute();
                    wup.wupVersion = current.getRequestVersion();
                    wup.writeInt32("", _ret);
                    wup.writeStruct("stRsp", stRsp);

                    current.doResponse(wup.encode());
                } else {
                    var os = new TafStream.JceOutputStream();
                    os.writeInt32(0, _ret);
                    os.writeStruct(2, stRsp);

                    current.doResponse(os.getBinBuffer());
                }
            }

            this.helloWorld(current, stReq, stRsp);

            return TafError.SUCCESS;
        }
        case 'inserData' : {
            if (current.getRequestVersion() === TafStream.Wup.WUP_VERSION) {
                var wup = new TafStream.UniAttribute();
                wup.wupVersion = current.getRequestVersion();
                wup.decode(BinBuffer);
                var stReq = wup.readStruct("stReq", Test.HelloWorldReq);
                var stRsp = wup.readStruct("stRsp", Test.HelloWorldRsp, new Test.HelloWorldRsp());
            } else {
                var is = new TafStream.JceInputStream(BinBuffer);
                var stReq = is.readStruct(1, true, Test.HelloWorldReq);
                var stRsp = is.readStruct(2, false, Test.HelloWorldRsp);
            }
            current.sendResponse = function (_ret, stRsp) {
                if (current.getRequestVersion() === TafStream.Wup.WUP_VERSION) {
                    var wup = new TafStream.UniAttribute();
                    wup.wupVersion = current.getRequestVersion();
                    wup.writeInt32("", _ret);
                    wup.writeStruct("stRsp", stRsp);

                    current.doResponse(wup.encode());
                } else {
                    var os = new TafStream.JceOutputStream();
                    os.writeInt32(0, _ret);
                    os.writeStruct(2, stRsp);

                    current.doResponse(os.getBinBuffer());
                }
            }

            this.inserData(current, stReq, stRsp);

            return TafError.SUCCESS;
        }
        case 'getData' : {
            if (current.getRequestVersion() === TafStream.Wup.WUP_VERSION) {
                var wup = new TafStream.UniAttribute();
                wup.wupVersion = current.getRequestVersion();
                wup.decode(BinBuffer);
                var stReq = wup.readStruct("stReq", Test.HelloWorldReq);
                var stRsp = wup.readStruct("stRsp", Test.HelloWorldRsp, new Test.HelloWorldRsp());
            } else {
                var is = new TafStream.JceInputStream(BinBuffer);
                var stReq = is.readStruct(1, true, Test.HelloWorldReq);
                var stRsp = is.readStruct(2, false, Test.HelloWorldRsp);
            }
            current.sendResponse = function (_ret, stRsp) {
                if (current.getRequestVersion() === TafStream.Wup.WUP_VERSION) {
                    var wup = new TafStream.UniAttribute();
                    wup.wupVersion = current.getRequestVersion();
                    wup.writeInt32("", _ret);
                    wup.writeStruct("stRsp", stRsp);

                    current.doResponse(wup.encode());
                } else {
                    var os = new TafStream.JceOutputStream();
                    os.writeInt32(0, _ret);
                    os.writeStruct(2, stRsp);

                    current.doResponse(os.getBinBuffer());
                }
            }

            this.getData(current, stReq, stRsp);

            return TafError.SUCCESS;
        }
    }
    return TafError.SERVER.FUNC_NOT_FOUND;
}

Test.HelloImp.prototype.test = function (current) {
    //TODO:
    assert.fail('test function not implemented');
}

Test.HelloImp.prototype.helloWorld = function (current, stReq, stRsp) {
    //TODO:
    assert.fail('helloWorld function not implemented');
}

Test.HelloImp.prototype.inserData = function (current, stReq, stRsp) {
    //TODO:
    assert.fail('inserData function not implemented');
}

Test.HelloImp.prototype.getData = function (current, stReq, stRsp) {
    //TODO:
    assert.fail('getData function not implemented');
}





